Feature/cdm line item
fivetran/dbt_recharge_source pull request #13
Opened 2024-06-26 22:15 UTC by fivetran-catfritz

## PR Overview
**This PR will address the following Issue/Feature:**

**This PR will result in the following new package version:**

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt run –full-refresh && dbt test
- [ ] dbt run (if incremental models are present) && dbt test

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked, tagged, and properly assigned
- [ ] All necessary documentation and version upgrades have been applied
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)
- [ ] BuildKite integration tests are passing
- [ ] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2024-06-28 19:03 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz no major code changes needed in this PR! The only changes required before approving are including the necessary documentation and CHANGELOG updates.

2024-06-28 19:03 UTC, fivetran-joemarkiewicz commented on macros/get_address_columns.sql
> +    {"name": "payment_method_id", "datatype": dbt.type_string()}
A customer _could_ have had `country` and/or `payment_method_id` as a passthrough column for this model. Let's be sure to list this as a potential breaking change once the CHANGELOG is generated.

2024-06-28 19:03 UTC, fivetran-joemarkiewicz commented on models/stg_recharge__checkout.sql
> +    {{ fivetran_utils.fill_pass_through_columns('recharge__checkout_passthrough_columns') }}
Be sure to include documentation for this new passthrough column once the docs are ready to be updated.

2024-06-28 19:03 UTC, fivetran-joemarkiewicz commented on models/tmp/stg_recharge__checkout.sql
> +{{ config(enabled=var('recharge__using_checkout', false)) }}
Be sure to document this variable once the docs are ready to be created

2024-06-28 19:03 UTC, fivetran-joemarkiewicz commented on integration_tests/seeds/checkout_data.csv
> +token, charge_id
Reminder to add more seed fields before release

2024-06-28 19:03 UTC, fivetran-joemarkiewicz commented on models/stg_recharge.yml
> +  - name: stg_recharge__checkout
Reminder to update the docs when ready

2024-06-28 19:03 UTC, fivetran-joemarkiewicz commented on models/src_recharge.yml
> +      - name: checkout
Reminder to update docs when ready

2024-06-28 19:03 UTC, fivetran-joemarkiewicz commented on models/stg_recharge__address.sql
> +        payment_method_id
We technically will want to make this a breaking change and call it out in the CHANGELOG. These fields _could_ have been used in the passthrough column variable and could result in a breaking run if they are still included.

2024-07-09 19:40 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz Looks great! Just one documentation question to address before approval.

2024-07-09 19:40 UTC, fivetran-joemarkiewicz commented on README.md
> +  recharge__checkout_enabled: false # Disables if you do not have the CHECKOUT table. Default is True.
Isn't the default `false`?

2024-07-09 20:36 UTC, fivetran-catfritz reviewed
This is now updated!

2024-07-09 20:36 UTC, fivetran-catfritz commented on models/stg_recharge__checkout.sql
> +    {{ fivetran_utils.fill_pass_through_columns('recharge__checkout_passthrough_columns') }}
Added.

2024-07-09 20:36 UTC, fivetran-catfritz commented on models/stg_recharge__address.sql
> +        payment_method_id
Updated!

2024-07-09 20:36 UTC, fivetran-catfritz commented on models/stg_recharge.yml
> +  - name: stg_recharge__checkout
Updated!

2024-07-09 20:36 UTC, fivetran-catfritz commented on integration_tests/seeds/checkout_data.csv
> +token, charge_id
Updated!

2024-07-09 20:36 UTC, fivetran-catfritz commented on macros/get_address_columns.sql
> +    {"name": "payment_method_id", "datatype": dbt.type_string()}
Updated!

2024-07-09 20:36 UTC, fivetran-catfritz commented on models/src_recharge.yml
> +      - name: checkout
Updated!

2024-07-09 20:36 UTC, fivetran-catfritz commented on models/tmp/stg_recharge__checkout.sql
> +{{ config(enabled=var('recharge__using_checkout', false)) }}
Added.

2024-07-09 20:36 UTC, fivetran-catfritz commented on README.md
> +  recharge__checkout_enabled: false # Disables if you do not have the CHECKOUT table. Default is True.
Yes, updated!

2024-07-09 20:54 UTC, fivetran-joemarkiewicz approved these changes
LGTM!

2024-08-13 19:41 UTC, fivetran-reneeli commented on models/src_recharge.yml
> +          - name: token
Do we want to add a unique test here?

2024-08-13 20:22 UTC, fivetran-reneeli approved these changes
looks good!

2024-08-14 16:11 UTC, merged